version: '3'

services:
  web:
    build: ./t_kontakta
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./t_kontakta:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - PGPASSWORD=password

