# Generated by Django 3.0.2 on 2020-04-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('vencode', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Артикул')),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField()),
                ('radius', models.PositiveSmallIntegerField()),
                ('weidth', models.PositiveSmallIntegerField()),
                ('profile', models.PositiveSmallIntegerField()),
                ('seasone', models.CharField(max_length=100, verbose_name='Сезонность')),
                ('producer', models.CharField(max_length=150, verbose_name='Производитель')),
                ('tire_model', models.CharField(max_length=150, verbose_name='Модель')),
                ('category', models.ManyToManyField(to='core.Category')),
            ],
            options={
                'verbose_name': 'Шина',
                'verbose_name_plural': 'Шины',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Tires')),
            ],
        ),
    ]
