# Generated by Django 3.0.2 on 2020-04-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200417_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Ссылка'),
        ),
    ]
