# Generated by Django 3.0.2 on 2020-05-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourcontacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='ourcontacts',
            name='description',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ourcontacts',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ourcontacts',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ourcontacts',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
