# Generated by Django 3.0.2 on 2020-05-17 13:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('our_contacts', '0002_auto_20200517_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcontacts',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
