# Generated by Django 3.0.2 on 2020-05-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tire_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Шиномонтаж', 'verbose_name_plural': 'Шиномонтаж'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='descriprion',
            new_name='description',
        ),
    ]
